export const audioMap = {
  "Hello there, superstar! Welcome to today's maths adventure!": "/assets/audio/audio_hello_there__superstar__welcome_to_today_s_maths_a_0.mp3",
  "Today, we're going to learn something really exciting.": "/assets/audio/audio_today__we_re_going_to_learn_something_really_excit_1.mp3",
  "Have you ever wondered how many toys you have altogether when you get more? That's exactly what we'll learn today!": "/assets/audio/audio_have_you_ever_wondered_how_many_toys_you_have_alto_2.mp3",
  "Are you ready to become a word problem champion?": "/assets/audio/audio_are_you_ready_to_become_a_word_problem_champion__3.mp3",
  "I know you can do it! Let's go!": "/assets/audio/audio_i_know_you_can_do_it__let_s_go__4.mp3",
  "Let's find out together!": "/assets/audio/audio_let_s_find_out_together__5.mp3",
  "I just know you're going to love what comes next!": "/assets/audio/audio_i_just_know_you_re_going_to_love_what_comes_next__6.mp3",
  "Let me tell you a story about Mia!": "/assets/audio/audio_let_me_tell_you_a_story_about_mia__7.mp3",
  "One morning, Mia brought 6 red apples to school.": "/assets/audio/audio_one_morning__mia_brought_6_red_apples_to_school__8.mp3",
  "Her friend Raju gave her 4 more green apples.": "/assets/audio/audio_her_friend_raju_gave_her_4_more_green_apples__9.mp3",
  "Mia looked at all her apples and wondered...": "/assets/audio/audio_mia_looked_at_all_her_apples_and_wondered____10.mp3",
  "How many apples do I have altogether?": "/assets/audio/audio_how_many_apples_do_i_have_altogether__11.mp3",
  "What do you think? How can Mia find out?": "/assets/audio/audio_what_do_you_think__how_can_mia_find_out__12.mp3",
  "Let's help Mia solve this!": "/assets/audio/audio_let_s_help_mia_solve_this__13.mp3",
  "Priya showed Mia a clever trick!": "/assets/audio/audio_priya_showed_mia_a_clever_trick__14.mp3",
  "She put the 6 red apples on one side.": "/assets/audio/audio_she_put_the_6_red_apples_on_one_side__15.mp3",
  "And the 4 green apples on the other side.": "/assets/audio/audio_and_the_4_green_apples_on_the_other_side__16.mp3",
  "Then she pushed them all together!": "/assets/audio/audio_then_she_pushed_them_all_together__17.mp3",
  "When we combine two groups, we ADD!": "/assets/audio/audio_when_we_combine_two_groups__we_add__18.mp3",
  "6 plus 4 equals 10 apples altogether!": "/assets/audio/audio_6_plus_4_equals_10_apples_altogether__19.mp3",
  "Great thinking! Adding means combining two groups into one big group!": "/assets/audio/audio_great_thinking__adding_means_combining_two_groups__20.mp3",
  "Then Wei Ming drew a special picture.": "/assets/audio/audio_then_wei_ming_drew_a_special_picture__21.mp3",
  "It's called a bar model!": "/assets/audio/audio_it_s_called_a_bar_model__22.mp3",
  "He drew two smaller bars. One for 6, and one for 4.": "/assets/audio/audio_he_drew_two_smaller_bars__one_for_6__and_one_for_4_23.mp3",
  "And he showed how together they make the big bar of 10!": "/assets/audio/audio_and_he_showed_how_together_they_make_the_big_bar_o_24.mp3",
  "Can you see how the two parts make the whole?": "/assets/audio/audio_can_you_see_how_the_two_parts_make_the_whole__25.mp3",
  "Part plus part equals whole!": "/assets/audio/audio_part_plus_part_equals_whole__26.mp3",
  "That's the secret! The parts always add up to the whole!": "/assets/audio/audio_that_s_the_secret__the_parts_always_add_up_to_the__27.mp3",
  "Mia was so excited!": "/assets/audio/audio_mia_was_so_excited__28.mp3",
  "She learned she could use number bonds, bar models, and even a number line to solve word problems.": "/assets/audio/audio_she_learned_she_could_use_number_bonds__bar_models_29.mp3",
  "Can we practice more?": "/assets/audio/audio_can_we_practice_more__30.mp3",
  "And so, the word problem adventure began!": "/assets/audio/audio_and_so__the_word_problem_adventure_began__31.mp3",
  "Now it's your turn to explore!": "/assets/audio/audio_now_it_s_your_turn_to_explore__32.mp3",
  "Let's try some hands-on activities! Are you ready?": "/assets/audio/audio_let_s_try_some_hands_on_activities__are_you_ready__33.mp3",
  "Let's try this together!": "/assets/audio/audio_let_s_try_this_together__34.mp3",
  "Take a moment to think.": "/assets/audio/audio_take_a_moment_to_think__35.mp3",
  "Press the Combine button to see what happens!": "/assets/audio/audio_press_the_combine_button_to_see_what_happens__36.mp3",
  "Now click the answer to check!": "/assets/audio/audio_now_click_the_answer_to_check__37.mp3",
  "Excellent work! You combined two groups perfectly!": "/assets/audio/audio_excellent_work__you_combined_two_groups_perfectly__38.mp3",
  "Now let's try something fun!": "/assets/audio/audio_now_let_s_try_something_fun__39.mp3",
  "Count along as you add each one!": "/assets/audio/audio_count_along_as_you_add_each_one__40.mp3",
  "You counted them all! Fantastic!": "/assets/audio/audio_you_counted_them_all__fantastic__41.mp3",
  "Now let's build a bar model!": "/assets/audio/audio_now_let_s_build_a_bar_model__42.mp3",
  "Can you find the right numbers for Part A and Part B?": "/assets/audio/audio_can_you_find_the_right_numbers_for_part_a_and_part_43.mp3",
  "Click the correct number for Part A first!": "/assets/audio/audio_click_the_correct_number_for_part_a_first__44.mp3",
  "Now find Part B!": "/assets/audio/audio_now_find_part_b__45.mp3",
  "You built the bar model perfectly! The parts make the whole!": "/assets/audio/audio_you_built_the_bar_model_perfectly__the_parts_make__46.mp3",
  "Here comes our frog friend!": "/assets/audio/audio_here_comes_our_frog_friend__47.mp3",
  "Press the Jump button to hop the frog forward!": "/assets/audio/audio_press_the_jump_button_to_hop_the_frog_forward__48.mp3",
  "Count each jump out loud!": "/assets/audio/audio_count_each_jump_out_loud__49.mp3",
  "The frog landed right where we expected!": "/assets/audio/audio_the_frog_landed_right_where_we_expected__50.mp3",
  "Counting on is such a cool trick for adding!": "/assets/audio/audio_counting_on_is_such_a_cool_trick_for_adding__51.mp3",
  "You've explored all the stations!": "/assets/audio/audio_you_ve_explored_all_the_stations__52.mp3",
  "You now know how to use story scenes, number bonds, bar models, and number lines!": "/assets/audio/audio_you_now_know_how_to_use_story_scenes__number_bonds_53.mp3",
  "Are you ready for the challenge?": "/assets/audio/audio_are_you_ready_for_the_challenge__54.mp3",
  "Let's play!": "/assets/audio/audio_let_s_play__55.mp3",
  "Read each word problem carefully.": "/assets/audio/audio_read_each_word_problem_carefully__56.mp3",
  "Look for clue words like altogether, in all, or how many.": "/assets/audio/audio_look_for_clue_words_like_altogether__in_all__or_ho_57.mp3",
  "I believe in you! Let's go!": "/assets/audio/audio_i_believe_in_you__let_s_go__58.mp3",
  "Take a moment to think about the answer.": "/assets/audio/audio_take_a_moment_to_think_about_the_answer__59.mp3",
  "You're a true maths champion!": "/assets/audio/audio_you_re_a_true_maths_champion__60.mp3",
  "Keep practicing and you'll be even better!": "/assets/audio/audio_keep_practicing_and_you_ll_be_even_better__61.mp3",
  "Good start! Try again to improve your score!": "/assets/audio/audio_good_start__try_again_to_improve_your_score__62.mp3",
  "Now let's think about what we've learned today.": "/assets/audio/audio_now_let_s_think_about_what_we_ve_learned_today__63.mp3",
  "The monkey mascot has some questions for you!": "/assets/audio/audio_the_monkey_mascot_has_some_questions_for_you__64.mp3",
  "Can you teach the mascot what you know?": "/assets/audio/audio_can_you_teach_the_mascot_what_you_know__65.mp3",
  "Great explanation! You really understand this!": "/assets/audio/audio_great_explanation__you_really_understand_this__66.mp3",
  "That's not quite right, but don't worry! Let's try the next one.": "/assets/audio/audio_that_s_not_quite_right__but_don_t_worry__let_s_try_67.mp3",
  "How do you feel about word problems now?": "/assets/audio/audio_how_do_you_feel_about_word_problems_now__68.mp3",
  "Be honest! Every answer is a great answer.": "/assets/audio/audio_be_honest__every_answer_is_a_great_answer__69.mp3",
  "You are an Addition Master!": "/assets/audio/audio_you_are_an_addition_master__70.mp3",
  "I'm so proud of you! Keep up the wonderful work!": "/assets/audio/audio_i_m_so_proud_of_you__keep_up_the_wonderful_work__71.mp3",
  "Great effort! You're getting better every day!": "/assets/audio/audio_great_effort__you_re_getting_better_every_day__72.mp3",
  "Come back and practice again anytime!": "/assets/audio/audio_come_back_and_practice_again_anytime__73.mp3",
  "Good start! Practice makes perfect!": "/assets/audio/audio_good_start__practice_makes_perfect__74.mp3",
  "Try again and watch your score grow!": "/assets/audio/audio_try_again_and_watch_your_score_grow__75.mp3",
  "Can you count them all?": "/assets/audio/audio_can_you_count_them_all__76.mp3",
  "That's right! Great thinking!": "/assets/audio/audio_that_s_right__great_thinking__77.mp3",
  "Excellent! You're a word problem superstar!": "/assets/audio/audio_excellent__you_re_a_word_problem_superstar__78.mp3",
  "Wonderful! You found the answer!": "/assets/audio/audio_wonderful__you_found_the_answer__79.mp3",
  "Brilliant! Keep up the amazing work!": "/assets/audio/audio_brilliant__keep_up_the_amazing_work__80.mp3",
  "Perfect! You're getting so good at this!": "/assets/audio/audio_perfect__you_re_getting_so_good_at_this__81.mp3",
  "Yes! You nailed it!": "/assets/audio/audio_yes__you_nailed_it__82.mp3",
  "Absolutely correct! Well done!": "/assets/audio/audio_absolutely_correct__well_done__83.mp3",
  "Amazing! You're on fire!": "/assets/audio/audio_amazing__you_re_on_fire__84.mp3",
  "Fantastic work! I'm so proud of you!": "/assets/audio/audio_fantastic_work__i_m_so_proud_of_you__85.mp3",
  "Spot on! You really understand addition!": "/assets/audio/audio_spot_on__you_really_understand_addition__86.mp3",
  "Not quite, but that's okay! Let's learn from this one.": "/assets/audio/audio_not_quite__but_that_s_okay__let_s_learn_from_this__87.mp3",
  "Oops! That wasn't the right answer, but don't worry. You'll get the next one!": "/assets/audio/audio_oops__that_wasn_t_the_right_answer__but_don_t_worr_88.mp3",
  "Almost! Let's try the next one. You can do it!": "/assets/audio/audio_almost__let_s_try_the_next_one__you_can_do_it__89.mp3",
  "That's alright! Mistakes help us learn.": "/assets/audio/audio_that_s_alright__mistakes_help_us_learn__90.mp3",
  "Keep trying! Every mistake makes you smarter!": "/assets/audio/audio_keep_trying__every_mistake_makes_you_smarter__91.mp3",
  "You're on a streak! Keep going!": "/assets/audio/audio_you_re_on_a_streak__keep_going__92.mp3",
  "Wow, look at you go! What a streak!": "/assets/audio/audio_wow__look_at_you_go__what_a_streak__93.mp3",
  "Unstoppable! What an amazing streak!": "/assets/audio/audio_unstoppable__what_an_amazing_streak__94.mp3",
  "You're on fire! Nothing can stop you!": "/assets/audio/audio_you_re_on_fire__nothing_can_stop_you__95.mp3"
};
