// src/utils/audioMap.js
// AUTO-GENERATED by scripts/generate_audio.js — do not edit by hand.
// Run `npm run generate-audio` to regenerate.

export const audioMap = {
  "Priya has 6 red stickers and gets 4 more blue stickers — how can pushing both groups together help us find how many she has altogether?": "assets/audio/audio_priya_has_6_red_stickers_and_gets_4_more_blue_stickers__0.mp3",
  "What happens to two separate groups of things when you combine them into one group?": "assets/audio/audio_what_happens_to_two_separate_groups_of_things_when_you__1.mp3",
  "A number bond shows two parts joining to make one whole — if one part is 8 and the other part is 5, what does the whole circle show?": "assets/audio/audio_a_number_bond_shows_two_parts_joining_to_make_one_whole_2.mp3",
  "Could the whole just be both parts added together?": "assets/audio/audio_could_the_whole_just_be_both_parts_added_together_3.mp3",
  "A bar model has two smaller bars sitting side by side, and one big bar underneath — what job does the big bar do?": "assets/audio/audio_a_bar_model_has_two_smaller_bars_sitting_side_by_side_a_4.mp3",
  "Could the big bar be showing the two smaller bars combined into one?": "assets/audio/audio_could_the_big_bar_be_showing_the_two_smaller_bars_combi_5.mp3",
  "A frog starts at 6 on a number line and hops forward 4 more spaces — where will it land, and why?": "assets/audio/audio_a_frog_starts_at_6_on_a_number_line_and_hops_forward_4__6.mp3",
  "Counting on from a number is another way of doing the very same thing as adding.": "assets/audio/audio_counting_on_from_a_number_is_another_way_of_doing_the_v_7.mp3",
  "Word problems often use clue words like altogether, in all, and how many more — what job do these words do?": "assets/audio/audio_word_problems_often_use_clue_words_like_altogether_in_a_8.mp3",
  "Could spotting the right clue word tell us which numbers to add?": "assets/audio/audio_could_spotting_the_right_clue_word_tell_us_which_number_9.mp3",
  "Priya brought 6 red stickers to school. Her classmate Wei Ming gave her 4 more blue stickers. Priya looked at all her stickers and wondered, how many stickers do I have altogether?": "assets/audio/audio_priya_brought_6_red_stickers_to_school_her_classmate_we_10.mp3",
  "Wei Ming has a trick! He put the 6 red stickers on one side and the 4 blue stickers on the other. Then he pushed them all together. When we combine two groups, we add, said Wei Ming. 6 plus 4 makes 10 stickers altogether!": "assets/audio/audio_wei_ming_has_a_trick_he_put_the_6_red_stickers_on_one_s_11.mp3",
  "Then Farhan drew a special picture called a bar model. He drew two smaller bars, one for 6 and one for 4, and showed how together they make one big bar of 10. The parts make the whole, he said.": "assets/audio/audio_then_farhan_drew_a_special_picture_called_a_bar_model_h_12.mp3",
  "Priya grinned. Now she could use number bonds, bar models, and even a number line to solve any addition word problem. Can we practice more, she asked. And so the word problem adventure began!": "assets/audio/audio_priya_grinned_now_she_could_use_number_bonds_bar_models_13.mp3",
  "Sticker Combine Mission!": "assets/audio/audio_sticker_combine_mission_14.mp3",
  "Push the two groups together, then tap the number that shows how many there are altogether.": "assets/audio/audio_push_the_two_groups_together_then_tap_the_number_that_s_15.mp3",
  "Bar Model Builder Mission!": "assets/audio/audio_bar_model_builder_mission_16.mp3",
  "Read the word problem, then tap the two parts to build the bar model and find the whole.": "assets/audio/audio_read_the_word_problem_then_tap_the_two_parts_to_build_t_17.mp3",
  "Number Line Hop Mission!": "assets/audio/audio_number_line_hop_mission_18.mp3",
  "Watch the frog hop along the number line, then type in the number where it lands.": "assets/audio/audio_watch_the_frog_hop_along_the_number_line_then_type_in_t_19.mp3",
  "Boss battle time! Answer every word problem correctly to win.": "assets/audio/audio_boss_battle_time_answer_every_word_problem_correctly_to_20.mp3",
  "Remember: find the two parts first, then add them together.": "assets/audio/audio_remember_find_the_two_parts_first_then_add_them_togethe_21.mp3",
  "Boss defeated! Fantastic addition word problem solving!": "assets/audio/audio_boss_defeated_fantastic_addition_word_problem_solving_22.mp3",
};
