export const audioMap = {
  "Word Problems Using Addition": "/assets/audio/audio_word_problems_using_addition_0.mp3",
  "Lesson 2.5. Learn to solve addition word problems": "/assets/audio/audio_lesson_2_5__learn_to_solve_addition_word_problems_1.mp3",
  "I'll teach you to solve word problems!": "/assets/audio/audio_i_ll_teach_you_to_solve_word_problems__2.mp3",
  "One morning, Mia brought 6 red apples to school. Her friend Raju gave her 4 more green apples. Mia looked at all her apples and wondered...": "/assets/audio/audio_one_morning__mia_brought_6_red_apples_to_school__h_3.mp3",
  "How many apples do I have altogether?": "/assets/audio/audio_how_many_apples_do_i_have_altogether__4.mp3",
  "Let's help Mia!": "/assets/audio/audio_let_s_help_mia__5.mp3",
  "Priya showed Mia a trick! She put the 6 red apples on one side and the 4 green apples on the other. Then she pushed them all together! When we combine two groups, we ADD! said Priya.": "/assets/audio/audio_priya_showed_mia_a_trick__she_put_the_6_red_apples_6.mp3",
  "6 plus 4 equals 10 apples altogether!": "/assets/audio/audio_6_plus_4_equals_10_apples_altogether__7.mp3",
  "Adding means combining!": "/assets/audio/audio_adding_means_combining__8.mp3",
  "Then Wei Ming drew a special picture called a bar model. He drew two smaller bars — one for 6 and one for 4 — and showed how together they make the big bar of 10! The parts make the whole! he said.": "/assets/audio/audio_then_wei_ming_drew_a_special_picture_called_a_bar__9.mp3",
  "Part plus Part equals Whole!": "/assets/audio/audio_part_plus_part_equals_whole__10.mp3",
  "Parts make the whole!": "/assets/audio/audio_parts_make_the_whole__11.mp3",
  "Mia was so excited! She learned she could use number bonds, bar models, and even a number line to solve word problems. Can we practice more? she asked. And so, the word problem adventure began!": "/assets/audio/audio_mia_was_so_excited__she_learned_she_could_use_numb_12.mp3",
  "Word problems — here we come!": "/assets/audio/audio_word_problems___here_we_come__13.mp3",
  "Your turn now!": "/assets/audio/audio_your_turn_now__14.mp3",
  "Find both parts to reveal the whole!": "/assets/audio/audio_find_both_parts_to_reveal_the_whole__15.mp3",
  "Great jumping!": "/assets/audio/audio_great_jumping__16.mp3",
  "Teach the mascot what you learned!": "/assets/audio/audio_teach_the_mascot_what_you_learned__17.mp3",
  "How do you feel about word problems?": "/assets/audio/audio_how_do_you_feel_about_word_problems__18.mp3",
  "Be honest — every answer is great!": "/assets/audio/audio_be_honest___every_answer_is_great__19.mp3",
  "Incredible! You are an Addition Master!": "/assets/audio/audio_incredible__you_are_an_addition_master__20.mp3",
  "Great effort! Keep practicing!": "/assets/audio/audio_great_effort__keep_practicing__21.mp3",
  "Good start! Try again to improve!": "/assets/audio/audio_good_start__try_again_to_improve__22.mp3",
  "That's right! Great thinking!": "/assets/audio/audio_that_s_right__great_thinking__23.mp3",
  "Excellent! You're a word problem superstar!": "/assets/audio/audio_excellent__you_re_a_word_problem_superstar__24.mp3",
  "Wonderful! You found the answer!": "/assets/audio/audio_wonderful__you_found_the_answer__25.mp3",
  "Brilliant! Keep up the amazing work!": "/assets/audio/audio_brilliant__keep_up_the_amazing_work__26.mp3",
  "Perfect! You're getting so good at this!": "/assets/audio/audio_perfect__you_re_getting_so_good_at_this__27.mp3",
  "Yes! You nailed it!": "/assets/audio/audio_yes__you_nailed_it__28.mp3",
  "Absolutely correct! Well done!": "/assets/audio/audio_absolutely_correct__well_done__29.mp3",
  "Amazing! You're on fire!": "/assets/audio/audio_amazing__you_re_on_fire__30.mp3",
  "Fantastic work! I'm so proud of you!": "/assets/audio/audio_fantastic_work__i_m_so_proud_of_you__31.mp3",
  "Spot on! You really understand addition!": "/assets/audio/audio_spot_on__you_really_understand_addition__32.mp3",
  "Not quite, but that's okay! Let's learn from this one.": "/assets/audio/audio_not_quite__but_that_s_okay__let_s_learn_from_this__33.mp3",
  "Oops! That wasn't the right answer, but don't worry. You'll get the next one!": "/assets/audio/audio_oops__that_wasn_t_the_right_answer__but_don_t_worr_34.mp3",
  "Almost! Let's try the next one. You can do it!": "/assets/audio/audio_almost__let_s_try_the_next_one__you_can_do_it__35.mp3",
  "That's alright! Mistakes help us learn.": "/assets/audio/audio_that_s_alright__mistakes_help_us_learn__36.mp3",
  "Keep trying! Every mistake makes you smarter!": "/assets/audio/audio_keep_trying__every_mistake_makes_you_smarter__37.mp3",
  "You're on a streak! Keep going!": "/assets/audio/audio_you_re_on_a_streak__keep_going__38.mp3",
  "Wow, look at you go! What a streak!": "/assets/audio/audio_wow__look_at_you_go__what_a_streak__39.mp3",
  "Unstoppable! What an amazing streak!": "/assets/audio/audio_unstoppable__what_an_amazing_streak__40.mp3",
  "You're on fire! Nothing can stop you!": "/assets/audio/audio_you_re_on_fire__nothing_can_stop_you__41.mp3"
};
